# Generated by Django 5.0.6 on 2024-05-23 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Accaount', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sub_cetagory',
            options={'verbose_name': 'Sub Cetagory'},
        ),
    ]
