# Generated by Django 5.0.6 on 2024-05-24 20:03

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_add_news_date_alter_add_news_vedio'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_news',
            name='news_slug',
            field=autoslug.fields.AutoSlugField(editable=False, null=True, populate_from='title', unique=True),
        ),
    ]
