# Generated by Django 5.0.6 on 2024-05-24 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_add_news_news_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.add_news')),
            ],
        ),
    ]
