# Generated by Django 5.0.6 on 2024-05-24 20:32

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0006_topnews'),
    ]

    operations = [
        migrations.AddField(
            model_name='topnews',
            name='news_slug',
            field=autoslug.fields.AutoSlugField(editable=False, null=True, populate_from='title', unique=True),
        ),
    ]
