# Generated by Django 5.0.6 on 2024-05-24 21:46

import autoslug.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0009_remove_topnews_news_slug_alter_topnews_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='Populer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('populer_slug', autoslug.fields.AutoSlugField(editable=False, null=True, populate_from='get_news_title', unique=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.add_news')),
            ],
        ),
    ]
