# Generated by Django 5.0.6 on 2024-05-25 08:18

import autoslug.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0010_populer'),
    ]

    operations = [
        migrations.CreateModel(
            name='News_populer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('populer_slug', autoslug.fields.AutoSlugField(editable=False, null=True, populate_from='name', unique=True)),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.add_news')),
            ],
        ),
    ]
