# Generated by Django 5.0.6 on 2024-05-25 09:24

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0011_news_populer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news_populer',
            name='populer_slug',
            field=autoslug.fields.AutoSlugField(editable=False, null=True, populate_from='get_news_title', unique=True),
        ),
    ]
