# Generated by Django 5.0.6 on 2024-05-25 09:51

import autoslug.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0013_alter_news_populer_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Super_news',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('super_slug', autoslug.fields.AutoSlugField(editable=False, null=True, populate_from='news_title', unique=True)),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.add_news')),
            ],
        ),
    ]
