# Generated by Django 5.0.6 on 2024-05-25 10:33

import autoslug.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0015_alter_topnews_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topnews',
            name='news',
            field=autoslug.fields.AutoSlugField(editable=False, null=True, populate_from='get_news_title', unique=True),
        ),
        migrations.CreateModel(
            name='top_news',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('top_slug', autoslug.fields.AutoSlugField(editable=False, null=True, populate_from='news_title', unique=True)),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Home.add_news')),
            ],
        ),
    ]
